[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_notepad = "3aoo9RF3FdfzrRnpYQawfxEYWkZMNCwQDyXU2evDzKvg"
[programs.localnet]
solana_notepad = "3aoo9RF3FdfzrRnpYQawfxEYWkZMNCwQDyXU2evDzKvg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/noble/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_notepad.json app/src/idl/solana_notepad.json"
