[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_notepad = "3aoo9RF3FdfzrRnpYQawfxEYWkZMNCwQDyXU2evDzKvg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/noble/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
